### ISSUE TITLE
register page 회원 database 등록 및 CSS 구현

### ISSUE THREAD

**Issue by Kimhyeonjung06** [garoo98/kw-OSS-proj-4#5]
register page의 HTML 부분 commit했으니 확인해 주시고 CSS 부분과 firebase에 회원 등록하는 부분 구현해주시기 바랍니다.

**Comment by seongOL** [comment]
firebase 회원가입 기능 부분 구현 완료했고 다음으로 이름 관련해서 추가 구현할 예정입니다.
